-- ==========================================
-- PostgreSQL 15 Authentication Module Schema
-- ==========================================
-- This schema represents a robust, highly optimized authentication structure
-- designed for enterprise workloads. It supports:
--   - UUID Keys (using native PostgreSQL gen_random_uuid())
--   - Role-Based Access Control (RBAC) via Users, Roles, and Permissions
--   - JWT Refresh Token Rotation and Revocation
--   - Automatic `updated_at` timestamp triggers
--   - Safe Soft-Delete support with partial uniqueness indexes
--   - Standardized audit fields (created_at, updated_at, deleted_at)
--   - Fast join path indexing on primary, composite, and foreign keys

-- Target Runtime: PostgreSQL 15+

-- Enable UUID extension if not already present (gen_random_uuid is native to 13+, but safe)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Standard Hibernate Envers revinfo table
CREATE TABLE IF NOT EXISTS revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- ==========================================
-- 1. UTILITY FUNCTIONS & TRIGGER PROCEDURES
-- ==========================================

-- Standardized trigger to gracefully maintain 'updated_at' audit field on changes
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ==========================================
-- 2. CORE SCHEMAS & TABLES
-- ==========================================

-- --- Table: users ---
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    mobile VARCHAR(20),
    user_type VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mobile_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_at TIMESTAMPTZ DEFAULT NULL,
    password_expires_at TIMESTAMPTZ DEFAULT NULL,
    last_login_at TIMESTAMPTZ DEFAULT NULL,
    last_password_change_at TIMESTAMPTZ DEFAULT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- --- Table: roles ---
CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    system_role BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- --- Table: permissions ---
CREATE TABLE IF NOT EXISTS permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    module VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    version BIGINT NOT NULL DEFAULT 0,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- --- Table: user_roles (Junction) ---
CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

-- --- Table: role_permissions (Junction) ---
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id UUID NOT NULL,
    permission_id UUID NOT NULL,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

-- --- Table: refresh_tokens ---
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    token_family_id VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ DEFAULT NULL,
    replaced_by_token_hash VARCHAR(255) DEFAULT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- --- Table: audit_logs ---
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(255),
    old_value JSONB,
    new_value JSONB,
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 3. INDEXES FOR PERFORMANCE & INTEGRITY
-- ==========================================

-- Partial unique index on user email.
-- Allows active emails to be unique, but allows soft-deleted users to retain historical emails.
CREATE UNIQUE INDEX idx_users_active_email 
ON users (LOWER(email)) 
WHERE deleted_at IS NULL;

-- Index for searching users by active/suspended status
CREATE INDEX idx_users_status 
ON users (is_active) 
WHERE deleted_at IS NULL;

-- Unique and standard indexes for roles. Soft delete filtering.
CREATE UNIQUE INDEX idx_roles_name_unique 
ON roles (LOWER(name)) 
WHERE deleted_at IS NULL;

-- Unique and standard indexes for permissions. Soft delete filtering.
CREATE UNIQUE INDEX idx_permissions_name_active 
ON permissions (LOWER(name)) 
WHERE deleted_at IS NULL;

-- High performance indexing on junction tables foreign keys (opposite fields in compound keys)
-- UserRoles: Primary key covers (user_id, role_id), so we need explicit index on role_id for backwards checks.
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);

-- RolePermissions: Primary key covers (role_id, permission_id), so we need explicit index on permission_id.
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);

-- Refresh token lookup optimization and expiration sweeping index.
CREATE UNIQUE INDEX idx_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (token_family_id);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_cleanup ON refresh_tokens (expires_at) WHERE revoked_at IS NULL AND deleted_at IS NULL;

-- Audit logs indexes
CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);

-- ==========================================
-- 4. TIMESTAMPTZ TRIGGERS (Auto Updated At)
-- ==========================================

DO $$
BEGIN
    -- users trigger
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_users_updated_at') THEN
        CREATE TRIGGER trg_users_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;

    -- roles trigger
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_roles_updated_at') THEN
        CREATE TRIGGER trg_roles_updated_at
        BEFORE UPDATE ON roles
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;

    -- permissions trigger
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_permissions_updated_at') THEN
        CREATE TRIGGER trg_permissions_updated_at
        BEFORE UPDATE ON permissions
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;

    -- user_roles trigger
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_user_roles_updated_at') THEN
        CREATE TRIGGER trg_user_roles_updated_at
        BEFORE UPDATE ON user_roles
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;

    -- role_permissions trigger
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_role_permissions_updated_at') THEN
        CREATE TRIGGER trg_role_permissions_updated_at
        BEFORE UPDATE ON role_permissions
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;

    -- refresh_tokens trigger
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_refresh_tokens_updated_at') THEN
        CREATE TRIGGER trg_refresh_tokens_updated_at
        BEFORE UPDATE ON refresh_tokens
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

