-- ==============================================================
-- Flyway Migration: V6__winner_management.sql
-- Module: Winner Selection & Post-Auction Decision Engine (Hardenings 5.1.1)
-- Target: PostgreSQL 15
-- ==============================================================

-- Create standard Envers revinfo table
CREATE TABLE IF NOT EXISTS revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- 1. Table: auction_winners (Hardened with snapshots)
CREATE TABLE IF NOT EXISTS auction_winners (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    auction_lot_id UUID NOT NULL UNIQUE,
    bidder_id UUID NOT NULL,
    bid_id UUID,
    status VARCHAR(50) NOT NULL,
    selection_type VARCHAR(50) NOT NULL,
    winning_amount NUMERIC(18,2) NOT NULL,
    seller_decision_at TIMESTAMPTZ,
    notes VARCHAR(1000),
    
    -- Immutable Snapshot Value Objects
    winner_company_name VARCHAR(255),
    winner_display_name VARCHAR(255),
    winner_anonymous_code VARCHAR(100),
    winner_bid_amount_snapshot NUMERIC(18,2),
    winner_bid_time_snapshot TIMESTAMPTZ,
    seller_company_snapshot VARCHAR(255),
    reserve_price_snapshot NUMERIC(18,2),
    currency_snapshot VARCHAR(10),
    tax_profile_snapshot VARCHAR(100),
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    
    CONSTRAINT fk_auction_winners_lot FOREIGN KEY (auction_lot_id) REFERENCES auction_lots (id) ON DELETE CASCADE,
    CONSTRAINT fk_auction_winners_bidder FOREIGN KEY (bidder_id) REFERENCES bidder_profiles (id),
    CONSTRAINT fk_auction_winners_bid FOREIGN KEY (bid_id) REFERENCES bids (id)
);

-- 2. Table: auction_results
CREATE TABLE IF NOT EXISTS auction_results (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    auction_lot_id UUID NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,
    highest_bid_amount NUMERIC(18,2),
    reserve_price NUMERIC(18,2),
    reserve_met BOOLEAN NOT NULL DEFAULT FALSE,
    winner_id UUID,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    
    CONSTRAINT fk_auction_results_lot FOREIGN KEY (auction_lot_id) REFERENCES auction_lots (id) ON DELETE CASCADE,
    CONSTRAINT fk_auction_results_winner FOREIGN KEY (winner_id) REFERENCES auction_winners (id) ON DELETE SET NULL
);

-- 3. Table: winner_histories (Hardened with actor/trace contexts)
CREATE TABLE IF NOT EXISTS winner_histories (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    winner_id UUID NOT NULL,
    previous_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    action_by VARCHAR(100) NOT NULL,
    action_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remarks VARCHAR(1000),
    
    -- Security Traceability & Correlation Context
    actor_id UUID,
    actor_type VARCHAR(50),
    reason VARCHAR(255),
    comments VARCHAR(1000),
    correlation_id VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    action_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    
    CONSTRAINT fk_winner_histories_winner FOREIGN KEY (winner_id) REFERENCES auction_winners (id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX idx_auction_winners_lot_id ON auction_winners (auction_lot_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_auction_winners_bidder_id ON auction_winners (bidder_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_auction_results_lot_id ON auction_results (auction_lot_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_winner_histories_winner_id ON winner_histories (winner_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_winner_histories_correlation ON winner_histories (correlation_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auction_winners_bid ON auction_winners (bid_id);
CREATE INDEX IF NOT EXISTS idx_auction_results_winner ON auction_results (winner_id);

-- 4. Envers Audit Tables (Enabling total auditability of snapshots)
CREATE TABLE IF NOT EXISTS auction_winners_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    auction_lot_id UUID,
    bidder_id UUID,
    bid_id UUID,
    status VARCHAR(50),
    selection_type VARCHAR(50),
    winning_amount NUMERIC(18,2),
    seller_decision_at TIMESTAMPTZ,
    notes VARCHAR(1000),
    
    winner_company_name VARCHAR(255),
    winner_display_name VARCHAR(255),
    winner_anonymous_code VARCHAR(100),
    winner_bid_amount_snapshot NUMERIC(18,2),
    winner_bid_time_snapshot TIMESTAMPTZ,
    seller_company_snapshot VARCHAR(255),
    reserve_price_snapshot NUMERIC(18,2),
    currency_snapshot VARCHAR(10),
    tax_profile_snapshot VARCHAR(100),
    
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_auction_winners_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_auction_winners_aud_rev ON auction_winners_aud (rev);

CREATE TABLE IF NOT EXISTS auction_results_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    auction_lot_id UUID,
    status VARCHAR(50),
    highest_bid_amount NUMERIC(18,2),
    reserve_price NUMERIC(18,2),
    reserve_met BOOLEAN,
    winner_id UUID,
    
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_auction_results_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_auction_results_aud_rev ON auction_results_aud (rev);

CREATE TABLE IF NOT EXISTS winner_histories_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    winner_id UUID,
    previous_status VARCHAR(50),
    new_status VARCHAR(50),
    action_by VARCHAR(100),
    action_at TIMESTAMPTZ,
    remarks VARCHAR(1000),
    
    actor_id UUID,
    actor_type VARCHAR(50),
    reason VARCHAR(255),
    comments VARCHAR(1000),
    correlation_id VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    action_timestamp TIMESTAMPTZ,
    
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_winner_histories_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_winner_histories_aud_rev ON winner_histories_aud (rev);
