spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eagle_auctioner
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true


logging:
  level:
    com.eagleauctioner: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
